pre-format

diff --git a/scripts/blade-queue b/scripts/blade-queue
--- a/scripts/blade-queue
+++ b/scripts/blade-queue
@@ -13,29 +13,25 @@ fi
 
 # parse argument
 if [ $# -eq 0 ]; then
+    echo "ERROR: Cluster .job file not specified"
+    exit 1
+else
+    JOB_FILE="$1"
     DIR=.
-else
-    DIR=$1
 fi
 
-# assume the first argument is the directory containing the job to execute
-# copy the directory to the blade gateway
+
 JOB_DIR=$(readlink -f $DIR)
-JOB_FILE=$JOB_DIR/main.job
+BASE_DIR=$(basename $JOB_DIR)
+BLADE_DIR=/home/$DEI_USER/BLADE/jobs
+LOCAL_DIR=$JOB_DIR
+FILTER_FILE=$LOCAL_DIR/.upload
 
-if [ ! -f $JOB_FILE ]; then
-    echo "main.job file is missing!"
-else
-    BASE_DIR=$(basename $JOB_DIR)
-    BLADE_DIR="/home/$DEI_USER/BLADE/jobs/${BASE_DIR}"
-    JOB_FILE="${BLADE_DIR}/main.job"
+blade-upload $DIR
 
-    echo "Copying files to DEI's ssh login machine..."
 
-    sshpass -f $DEI_PW_FILE rsync --progress -avz -e ssh "${JOB_DIR}"  $DEI_USER@login.dei.unipd.it:/home/$DEI_USER/blade/jobs
-
-    # enqueu the job
-    cmd="cd ${BLADE_DIR}; qsub main.job";
-    echo $cmd | sshpass -f $DEI_PW_FILE ssh -T -o StrictHostKeyChecking=no $DEI_USER@login.dei.unipd.it
-fi
+# enqueu the job
+cmd="cd $BLADE_DIR/$BASE_DIR; qsub $JOB_FILE";
+blade-command "$cmd"
+blade-stat
 
